#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include "Audio.h"

// --- WiFi Credentials ---
const char* ssid = "SmS_jiofi";
const char* password = "sms123458956";

// --- Gemini API Configuration ---
// IMPORTANT: Replace "YOUR_GEMINI_API_KEY" with your actual Gemini API key
const char* gemini_api_key = "AIzaSyBHm9q_6e0isIHAwzTADjqXyMSRiyueYhs";
const char* gemini_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=";
const char* temperature_gemini = "0.9"; // Gemini recommends a slightly higher temperature for creativity
const char* max_output_tokens_gemini = "100"; // Increased max tokens for potentially longer responses

String Question = "";

#define I2S_DOUT      25
#define I2S_BCLK      27
#define I2S_LRC       26

Audio audio;

void setup()
{
  Serial.begin(115200);

  WiFi.mode(WIFI_STA);
  WiFi.disconnect();

  while (!Serial);

  // Wait for WiFi connection
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(1000);
    Serial.print(".");
  }
  Serial.println("connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
  audio.setVolume(100);
}

void loop()
{
  Serial.print("Ask your Question : ");
  Question = ""; // Clear previous question
  while (!Serial.available())
  {
    audio.loop();
  }
  while (Serial.available())
  {
    char add = Serial.read();
    if (add == '\n' || add == '\r') { // Detect newline or carriage return as end of input
      break;
    }
    Question = Question + add;
    delay(1);
  }
  Question.trim(); // Remove any leading/trailing whitespace

  if (Question.length() == 0) {
    Serial.println("No question entered. Please try again.");
    return; // Skip API call if no question
  }

  Serial.print("Sending Question: ");
  Serial.println(Question);

  HTTPClient https;

  // Construct the full Gemini API URL
  String full_gemini_url = String(gemini_endpoint) + gemini_api_key;

  if (https.begin(full_gemini_url)) {
    https.addHeader("Content-Type", "application/json");

    // Construct the JSON payload for Gemini
    String payload = "{\"contents\":[{\"parts\":[{\"text\":\"" + Question + "\"}]}],\"generationConfig\":{\"temperature\":" + temperature_gemini + ",\"maxOutputTokens\":" + max_output_tokens_gemini + "}}";

    Serial.println("Sending Payload:");
    Serial.println(payload);

    int httpCode = https.POST(payload);

    if (httpCode == HTTP_CODE_OK) {
      String response_payload = https.getString();
      Serial.println("Gemini Response:");
      Serial.println(response_payload);

      DynamicJsonDocument doc(2048); // Increased buffer size for potentially larger responses
      DeserializationError error = deserializeJson(doc, response_payload);

      if (error) {
        Serial.print("deserializeJson() failed: ");
        Serial.println(error.c_str());
      } else {
        // Parse the Gemini response
        // The structure is typically: choices[0].text for content.
        // It might be nested under "candidates" -> "content" -> "parts" -> "text"
        String Answer = "";
        if (doc.containsKey("candidates") && doc["candidates"][0].containsKey("content") && doc["candidates"][0]["content"].containsKey("parts") && doc["candidates"][0]["content"]["parts"][0].containsKey("text")) {
           Answer = doc["candidates"][0]["content"]["parts"][0]["text"].as<String>();
        } else {
            Serial.println("Could not find 'text' in Gemini response. Response structure might have changed or no text generated.");
            if (doc.containsKey("promptFeedback") && doc["promptFeedback"].containsKey("blockReason")) {
                Serial.print("Blocked reason: ");
                Serial.println(doc["promptFeedback"]["blockReason"].as<String>());
            }
        }

        if (Answer.length() > 0) {
          Serial.print("Answer : ");
          Serial.println(Answer);
          audio.connecttospeech(Answer.c_str(), "en");
        } else {
          Serial.println("No answer generated by Gemini.");
        }
      }
    }
    else {
      Serial.printf("[HTTPS] POST... failed, error: %d - %s\n", httpCode, https.errorToString(httpCode).c_str());
      String error_response = https.getString();
      Serial.print("Error Response: ");
      Serial.println(error_response);
    }
    https.end();
  }
  else {
    Serial.printf("[HTTPS] Unable to connect to Gemini API\n");
  }

  // Small delay to prevent rapid-fire requests
  delay(100);
}

void audio_info(const char *info) {
  Serial.print("audio_info: "); Serial.println(info);
}